### ISSUE TITLE
Feat : 답변 상태에 따른 분기 처리를 구현합니다. 

### ISSUE THREAD

**Issue by hyunw9** [Team-Clody/Clody_server#144]
## 📝  To-do
요구사항 
- [ ] 버전 객체 매핑
- [ ] 당일 일기를 삭제한 사람은 답변을 받을 수 없음
- [ ] 답변 요청을 할 때, 삭제된 답변인지 체크 후 답변 요청 해야함
