### ISSUE TITLE
Feat : 초기 설정을 진행합니다. 

### ISSUE THREAD

**Issue by hyunw9** [Team-Clody/Clody_server#3]
## 📌  Feature Issue
초기 패키지 구조, API 문서 작성 구조를 정의합니다. 

## 📝  To-do

- [x] RestDocs 설정 
- [x] 전역 에러 설정 
- [x] 성공 / 실패 Enum 설정 
- [x] Api 통일 응답 값 설정 
- [x] 종속성 설정
